blueprint:
  name: Adaptive Humidity Baseline
  description: >
    Creates a template SENSOR whose state is an adaptive humidity baseline (%).
    Baseline follows normal drift (season/AC) but freezes during large rises (showers)
    and can optionally freeze while the fan is ON.

    Use this blueprint via YAML under `template:` with `use_blueprint` (see examples below).
  domain: template
  author: asucrews
  homeassistant:
    min_version: 2024.6.0
  input:
    humidity_sensor:
      name: Humidity sensor
      selector:
        entity:
          domain: sensor

    fan_entity:
      name: Fan or fan switch entity
      description: Entity that represents the exhaust fan (fan.* or switch.*)
      selector:
        entity:
          filter:
            - domain: fan
            - domain: switch

    freeze_while_fan_on:
      name: Freeze baseline while fan is ON
      default: true
      selector:
        boolean: {}

    big_rise_freeze:
      name: Freeze baseline when humidity rises this much above baseline (%)
      description: If current humidity is >= baseline + this value, baseline stops moving.
      default: 3.0
      selector:
        number:
          min: 0.0
          max: 20.0
          step: 0.1
          unit_of_measurement: "%"

    settle_band:
      name: Small-rise band (%)
      description: If humidity is only slightly above baseline (within this band), baseline slowly follows upward.
      default: 1.0
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.1
          unit_of_measurement: "%"

    alpha_up:
      name: Baseline follow-up rate (0..1)
      description: How fast baseline follows small upward drift (season/AC). Lower = slower.
      default: 0.05
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01

    alpha_down:
      name: Baseline follow-down rate (0..1)
      description: How fast baseline follows downward drift. Higher = faster.
      default: 0.25
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01

    clamp_min:
      name: Clamp minimum (%)
      default: 0
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

    clamp_max:
      name: Clamp maximum (%)
      default: 100
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

variables:
  h: !input humidity_sensor
  fan: !input fan_entity
  freeze_fan: !input freeze_while_fan_on
  big_rise: !input big_rise_freeze
  band: !input settle_band
  a_up: !input alpha_up
  a_dn: !input alpha_down
  cmin: !input clamp_min
  cmax: !input clamp_max

triggers:
  - trigger: state
    entity_id: !input humidity_sensor
  - trigger: time_pattern
    minutes: "/5"

sensor:
  unit_of_measurement: "%"
  device_class: humidity
  state_class: measurement
  availability: >
    {{ is_number(states(h)) }}
  state: >-
    {% set cur_raw = states(h) | float(none) %}
    {% if cur_raw is none %}
      {{ this.state | default('unknown') }}
    {% else %}
      {% set cur = [cmax, [cmin, cur_raw]|max] | min %}
      {% set prev = this.state | float(cur) %}
      {% set fan_on = (freeze_fan and is_state(fan, 'on')) %}
      {% set rise = cur - prev %}

      {% if fan_on %}
        {% set base = prev %}
      {% else %}
        {% if rise >= big_rise %}
          {% set base = prev %}
        {% elif cur <= prev %}
          {% set base = (prev*(1-a_dn) + cur*a_dn) %}
        {% elif (cur - prev) < band %}
          {% set base = (prev*(1-a_up) + cur*a_up) %}
        {% else %}
          {% set base = prev %}
        {% endif %}
      {% endif %}

      {{ base | round(1) }}
    {% endif %}