
blueprint:
  name: WITB Lights OFF Hook - VZW31-SN Switch + Bulb
  description: >
    Profile for turning lights OFF based on VZW31-SN Switch.
    Accepts dynamic parameters for lights and transition logic.
  domain: script
  input:
    vzw31_entity:
      name: "VZW31-SN Switch"
      description: "Entity ID of the VZW31-SN switch"
      selector:
        entity:
          domain: switch
    zwave_node_status_sensor:
      name: "Z-Wave Node Status"
      description: "Entity for monitoring the Z-Wave node status"
      selector:
        entity:
          domain: sensor
    ping_button_sensor:
      name: "Ping Button Sensor"
      description: "Entity for pinging the switch to wake up"
      selector:
        entity:
          domain: binary_sensor
    local_protection_select:
      name: "Local Protection"
      description: "Entity for local protection, if applicable"
      selector:
        entity:
          domain: select
    sbm_last_reset_helper:
      name: "SBM Reset Helper"
      description: "Helper to track the last SBM reset time"
      selector:
        entity:
          domain: sensor
    notify_id:
      name: "Notification ID"
      description: "Notification ID for status updates"
      selector:
        text:
          max_length: 100
  fields:
    lights:
      description: "List of lights to turn off"
      example: "['light.office', 'light.living_room']"
    brightness_pct:
      description: "Brightness percentage for lights (0-100)"
      example: 100
    transition:
      description: "Time in seconds to transition the lights"
      example: 5
    reason:
      description: "Reason for turning off lights"
      example: "no motion detected"
    is_night:
      description: "Boolean flag if it's night time"
      example: true
    lux_value:
      description: "Lux value for light level"
      example: 300
    lux_threshold:
      description: "Threshold lux value to trigger action"
      example: 150
  source_url: "https://github.com/asucrews/ha-blueprints/blob/main/blueprints/script/witb_switch_light_profiles/v1/witb_lights_off_hook_profile_vzw31_sn_switch_bulb_v1_9.yaml"
  code_url: "https://github.com/asucrews/ha-blueprints/blob/main/blueprints/script/witb_switch_light_profiles/v1/witb_lights_off_hook_profile_vzw31_sn_switch_bulb_v1_9.yaml"
