blueprint:
  name: "WITB Switch Light Profiles — SBM Cooldown Active"
  description: >
    Creates a trigger-based binary_sensor that is ON while the SBM reset cooldown
    window is still active.

    Pair it with the tracker sensor created by:
      WITB Switch Light Profiles — Last SBM Reset Tracker
  domain: template
  input:
    default_entity_id:
      name: Default entity_id
      description: "Example: binary_sensor.office_vzw31_sbm_cooldown_active"
      selector:
        text: {}
    last_reset_sensor:
      name: Last SBM reset tracker sensor
      selector:
        entity:
          domain: sensor
    cooldown_seconds:
      name: Cooldown (seconds)
      default: 600
      selector:
        number:
          min: 0
          max: 7200
          mode: slider
          step: 30
          unit_of_measurement: s

variables:
  last_reset_sensor: !input last_reset_sensor
  cooldown_seconds: !input cooldown_seconds

triggers:
  - trigger: state
    entity_id: !input last_reset_sensor
  - trigger: time_pattern
    minutes: "/1"

binary_sensor:
  default_entity_id: !input default_entity_id
  icon: mdi:timer-sand
  state: >-
    {% set s = states(last_reset_sensor) %}
    {% set cd = cooldown_seconds | int(0) %}
    {% if cd <= 0 %}
      false
    {% elif s in ['unknown','unavailable',''] %}
      false
    {% else %}
      {% set dt = as_datetime(s) %}
      {% if dt is none %}
        false
      {% else %}
        {{ (as_timestamp(now()) - as_timestamp(dt)) < cd }}
      {% endif %}
    {% endif %}
