blueprint:
  name: "WITB Switch Light Profiles — SBM Cooldown Remaining"
  description: >
    Creates a trigger-based sensor showing remaining cooldown seconds until the
    next SBM reset is allowed.

    Pair it with the tracker sensor created by:
      WITB Switch Light Profiles — Last SBM Reset Tracker
  domain: template
  input:
    default_entity_id:
      name: Default entity_id
      description: "Example: sensor.office_vzw31_sbm_cooldown_remaining"
      selector:
        text: {}
    last_reset_sensor:
      name: Last SBM reset tracker sensor
      selector:
        entity:
          domain: sensor
    cooldown_seconds:
      name: Cooldown (seconds)
      default: 600
      selector:
        number:
          min: 0
          max: 7200
          mode: slider
          step: 30
          unit_of_measurement: s

variables:
  last_reset_sensor: !input last_reset_sensor
  cooldown_seconds: !input cooldown_seconds

triggers:
  - trigger: state
    entity_id: !input last_reset_sensor
  - trigger: time_pattern
    minutes: "/1"

sensor:
  default_entity_id: !input default_entity_id
  icon: mdi:timer-sand
  unit_of_measurement: "s"
  state: >-
    {% set s = states(last_reset_sensor) %}
    {% set cd = cooldown_seconds | int(0) %}
    {% if cd <= 0 %}
      0
    {% elif s in ['unknown','unavailable',''] %}
      0
    {% else %}
      {% set dt = as_datetime(s) %}
      {% if dt is none %}
        0
      {% else %}
        {% set elapsed = (as_timestamp(now()) - as_timestamp(dt)) | int(0) %}
        {{ [0, (cd - elapsed)] | max }}
      {% endif %}
    {% endif %}
