blueprint:
  name: "WITB Lights OFF Hook (v1)"
  description: >
    Script blueprint used as a hook for WITB+ Actions.
    Expects WITB to call this script and pass:
      - lights (list of light entity_ids)
      - transition (seconds, optional)
      - is_night, lux_value, lux_threshold, reason (optional)

    v1 behavior: directly calls light.turn_off on the passed lights.
  domain: script
  homeassistant:
    min_version: 2024.6.0

mode: restart

fields:
  lights:
    name: Lights to control
    description: "List of light entity_ids to turn off. (Passed by WITB+ Actions)"
    required: true
    selector:
      entity:
        domain: light
        multiple: true
  transition:
    name: Transition (seconds)
    description: "Transition time in seconds. Optional; defaults to 0."
    required: false
    selector:
      number:
        min: 0
        max: 60
        mode: slider
        step: 0.5
  is_night:
    name: is_night
    description: "Optional context from WITB."
    required: false
    selector:
      boolean: {}
  lux_value:
    name: lux_value
    description: "Optional context from WITB."
    required: false
    selector:
      number:
        min: 0
        max: 100000
        mode: box
        step: 1
  lux_threshold:
    name: lux_threshold
    description: "Optional context from WITB."
    required: false
    selector:
      number:
        min: 0
        max: 100000
        mode: box
        step: 1
  reason:
    name: reason
    description: "Optional context from WITB (e.g., vacant_lights_off, startup_cleanup)."
    required: false
    selector:
      text: {}

sequence:
  - variables:
      _transition: "{{ transition | default(0) | float(0) }}"
      _lights: >-
        {% set v = lights | default([]) %}
        {% if v is string %}
          {{ [v] }}
        {% elif v is mapping and v.entity_id is defined %}
          {{ v.entity_id }}
        {% else %}
          {{ v }}
        {% endif %}

  - condition: template
    value_template: "{{ _lights is defined and (_lights | length > 0) }}"

  - action: light.turn_off
    target:
      entity_id: "{{ _lights }}"
    data:
      transition: "{{ _transition }}"
