blueprint:
  name: Smart Vents - Flair (0.2.0)
  homeassistant:
    min_version: 2024.6.0
  description: >
    <br/>
    <br/>
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/smart_vents/flair.yaml
  input:
    required_entities:
      name: Required Entities
      description: The required entities for this automation
      collapsed: false
      input:
        start_time:
          name: Start Time
          description: Set the start time.
          default: 00:00:00
          selector:
            time:
    optional_entities:
      name: Optional Entities
      description: The optional entities for this automation
      collapsed: true
      input:

variables:

trigger:
  - platform: time
    at: !input start_time
    id: time_1

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - time_1
        sequence:
          -

mode: single
max: silent