blueprint:
  name: Reset Room Direction to Idle
  description: >
    Resets an input_select to "Idle" if no motion has been detected for a specified amount of time.
  domain: automation
  input:
    motion_on_time:
      name: Motion ON Timestamp
      selector:
        entity:
          domain: input_datetime
    direction_select:
      name: Room Direction Select
      selector:
        entity:
          domain: input_select
    idle_after_minutes:
      name: Idle Timeout (minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
          mode: slider

trigger:
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: template
    value_template: >
      {{
        now().timestamp() - (state_attr(input.motion_on_time, 'timestamp') | float(0))
        > (input.idle_after_minutes | int(5)) * 60
      }}
  - condition: template
    value_template: >
      {{ states(input.direction_select) != "Idle" }}

action:
  - action: input_select.select_option
    target:
      entity_id: !input direction_select
    data:
      option: "Idle"
