blueprint:
  name: "Person: Status Update Fork (1.2.0)"
  homeassistant:
    min_version: 2024.8.0
  description: >
    Making Home Assistant’s Presence Detection not so Binary
    https://gist.github.com/cliffordwhansen/aa993e4173d2ce2e44fc6a0cb0af3599
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/person_status_update/person_status_update.yaml
  input:
    required_entities:
      name: Required Entities
      description: The required entities for this automation
      collapsed: false
      input:
        person_entity:
          name: Person entity
          description: The person entity to track
          selector:
            entity:
              domain: person
        person_input_select:
          name: Input select
          description: The input select that tracks the person's status
          selector:
            entity:
              domain: input_select
    optional_entities:
      name: Optional Entities
      description: The optional entities for this automation
      collapsed: true
      input:
        time_till_marked_away:
          name: Time till marked away
          description: How long to wait in "Just Left" before getting set as "Away"
          default: 10
          selector:
            number:
              min: 0
              max: 60
              unit_of_measurement: minutes
        time_till_marked_home:
          name: Time till marked home
          description: How long to wait in "Just Arrived" before getting set as "Home"
          default: 10
          selector:
            number:
              min: 0
              max: 60
              unit_of_measurement: minutes
        time_till_marked_extended_away:
          name: Time till marked extended away
          description: How long to wait in "Away" before being set to "Extended Away"
          default: 24
          selector:
            number:
              min: 0
              max: 168
              unit_of_measurement: hours

trigger:
  - platform: state
    entity_id: !input person_device_tracker
    to: home
    id: device_tracker_home
  - platform: state
    entity_id: !input person_input_select
    for:
      minutes: !input time_till_marked_home
    id: input_select_wait_arrived
    to: Just Arrived
  - platform: state
    entity_id: !input person_input_select
    from: Just Left
    to: Just Arrived
    id: input_select_debounce
  - platform: state
    entity_id: !input person_device_tracker
    from: home
    id: device_tracker_not_home
  - platform: state
    entity_id: !input person_input_select
    to: Just Left
    for:
      minutes: !input time_till_marked_away
    id: input_select_wait_left
  - platform: state
    entity_id: !input person_input_select
    to: Away
    for:
      hours: !input time_till_marked_extended_away
    id: input_select_wait_away

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: device_tracker_home # enter home zone within X minutes
          - condition: state
            entity_id: !input person_input_select
            state: Just Left
        sequence:
          - action: input_select.select_option
            target:
              entity_id: !input person_input_select
            data:
              option: Home
      - conditions:
          - condition: trigger
            id: device_tracker_home # enter home zone
        sequence:
          - action: input_select.select_option
            target:
              entity_id: !input person_input_select
            data:
              option: Just Arrived
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: input_select_wait_arrived
              - condition: trigger
                id: input_select_debounce
        sequence:
          - action: input_select.select_option
            target:
              entity_id: !input person_input_select
            data:
              option: Home
      - conditions:
          - condition: trigger
            id: device_tracker_not_home # left the home zone
        sequence:
          - action: input_select.select_option
            target:
              entity_id: !input person_input_select
            data:
              option: Just Left
      - conditions:
          - condition: trigger
            id: input_select_wait_left # away after X minutes
        sequence:
          - action: input_select.select_option
            target:
              entity_id: !input person_input_select
            data:
              option: Away
    default:
      - condition: trigger
        id: input_select_wait_away # extended away
      - action: input_select.select_option
        target:
          entity_id: !input person_input_select
        data:
          option: Extended Away

mode: single
max_exceeded: silent
