blueprint:
  name: Lights Based on Sun (Twilight Redundancy) (0.3.2)
  description: >
    Turns lights on after sunset and off at sunrise using three twilight thresholds
    for both ON and OFF to ensure redundancy. Also restores lights if manually turned off at night.
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/lights_sunset/lights_at_sunset.yaml
  input:
    front_lights:
      name: Front Door Lights
      selector:
        target:
          entity:
            domain: light
    garage_lights:
      name: Garage Door Lights
      selector:
        target:
          entity:
            domain: light
    string_lights:
      name: String Lights (Optional)
      default: []
      selector:
        target:
          entity:
            domain: light
    sun_sensor:
      name: Sun Solar Rising Sensor
      default: sensor.sun_solar_rising
      selector:
        entity:
          domain: sensor
    sun_phase_sensor:
      name: Home Sun Phase Sensor
      default: sensor.home_sun_phase
      selector:
        entity:
          domain: sensor

trigger:
  # SUNSET PHASES (Redundant ON triggers)
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: -6
    id: civil_twilight_on
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: -12
    id: nautical_twilight_on
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: -18
    id: astro_twilight_on
  # SUNRISE PHASES (Redundant OFF triggers)
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -18
    id: astro_twilight_off
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -12
    id: nautical_twilight_off
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -6
    id: civil_twilight_off
  # Manual light off triggers (restore during night)
  - platform: state
    entity_id: !input front_lights
    to: "off"
    id: front_door_manual_off
  - platform: state
    entity_id: !input garage_lights
    to: "off"
    id: garage_door_manual_off

action:
  - choose:
      # === LIGHTS ON at sunset (redundant triggers) ===
      - conditions:
          - condition: trigger
            id:
              - civil_twilight_on
              - nautical_twilight_on
              - astro_twilight_on
          - condition: template
            value_template: "{{ is_state(inputs.sun_sensor, 'False') }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input front_lights
          - action: light.turn_on
            target:
              entity_id: !input garage_lights
          - condition: template
            value_template: >
              {{ expand(inputs.string_lights) | selectattr('state', 'eq', 'off') | list | count > 0 }}
          - action: light.turn_on
            data:
              brightness_pct: 100
              color_temp_kelvin: 6500
            target:
              entity_id: !input string_lights
      # === LIGHTS OFF at sunrise (redundant triggers) ===
      - conditions:
          - condition: trigger
            id:
              - civil_twilight_off
              - nautical_twilight_off
              - astro_twilight_off
          - condition: template
            value_template: "{{ is_state(inputs.sun_sensor, 'True') }}"
        sequence:
          - action: light.turn_off
            target:
              entity_id:
                - !input front_lights
                - !input garage_lights
                - !input string_lights
      # === FRONT LIGHTS RESTORE at night ===
      - conditions:
          - condition: trigger
            id: front_door_manual_off
          - condition: state
            entity_id: !input sun_phase_sensor
            state: "night"
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input front_lights
          - condition: template
            value_template: >
              {{ expand(inputs.string_lights) | selectattr('state', 'eq', 'off') | list | count > 0 }}
          - action: light.turn_on
            data:
              brightness_pct: 100
              color_temp_kelvin: 6500
            target:
              entity_id: !input string_lights
      # === GARAGE LIGHTS RESTORE at night ===
      - conditions:
          - condition: trigger
            id: garage_door_manual_off
          - condition: state
            entity_id: !input sun_phase_sensor
            state: "night"
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input garage_lights
mode: single
