blueprint:
  name: LUX Sensor Stable (0.1.0)
  homeassistant:
    min_version: 2024.5.0
  description: >
    <br/>
    <br/>
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/lux_sensor/lux_sensor.yaml
  input:
    lux_sensor:
      name: LUX Sensor
      description: >
        <br/>
        <br/>
      selector:
        entity:
          domain:
            - sensor
          multiple: false
    status_boolean:
      name: Binary Sensor
      description: >
        <br/>
        <br/>
      selector:
        entity:
          domain:
            - input_boolean
          multiple: false
    day_above_lux_level:
      name: Above LUX level for day time
      description: >
        <br/>
        <br/>
      default: 0
      selector:
        number:
          min: 0
          max: 250
          step: 10
          unit_of_measurement: lx
          mode: slider
    day_below_lux_level:
      name: Below LUX level for day time
      description: >
        <br/>
        <br/>
      default: 0
      selector:
        number:
          min: 0
          max: 250
          step: 10
          unit_of_measurement: lx
          mode: slider
    night_above_lux_level:
      name: Above LUX level for night time
      description: >
        <br/>
        <br/>
      default: 0
      selector:
        number:
          min: 0
          max: 250
          step: 10
          unit_of_measurement: lx
          mode: slider
    night_below_lux_level:
      name: Below LUX level for night time
      description: >
        <br/>
        <br/>
      default: 0
      selector:
        number:
          min: 0
          max: 250
          step: 10
          unit_of_measurement: lx
          mode: slider

variables:
  lux_sensor: !input lux_sensor
  status_boolean: !input status_boolean
  day_above_lux_level: !input day_above_lux_level
  day_below_lux_level: !input day_below_lux_level
  night_above_lux_level: !input night_above_lux_level
  night_below_lux_level: !input night_below_lux_level

trigger:
  - platform: numeric_state
    entity_id: !input lux_sensor
    above: !input day_above_lux_level
    id: Light is on at day
  - platform: numeric_state
    entity_id: !input lux_sensor
    below: !input day_below_lux_level
    id: Light is off at day
  - platform: numeric_state
    entity_id: !input lux_sensor
    above: !input day_above_lux_level
    id: Light is on at night
  - platform: numeric_state
    entity_id: !input lux_sensor
    below: !input day_below_lux_level
    id: Light is off at night

action:
  - choose:
      - conditions:
          - condition: sun
            before: sunset
            after: sunrise
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - Light is on at day
                sequence:
                  - service: input_boolean.turn_on
                    metadata: {}
                    data: {}
                    target:
                      entity_id: !input status_boolean
              - conditions:
                  - condition: trigger
                    id:
                      - Light is off at day
                sequence:
                  - service: input_boolean.turn_off
                    metadata: {}
                    data: {}
                    target:
                      entity_id: !input status_boolean
      - conditions:
          - condition: sun
            before: sunrise
            after: sunset
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - Light is on at night
                sequence:
                  - service: input_boolean.turn_on
                    metadata: {}
                    data: {}
                    target:
                      entity_id: !input status_boolean
              - conditions:
                  - condition: trigger
                    id:
                      - Light is off at night
                sequence:
                  - service: input_boolean.turn_off
                    metadata: {}
                    data: {}
                    target:
                      entity_id: !input status_boolean
