blueprint:
  name: LUX Sensor (0.1.0rc10)
  description: >
    <br/>
    <br/>
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/lux_sensor/lux_sensor.yaml
  input:
    lux_sensor:
      name: LUX Sensor
      description: >
        <br/>
        <br/>
      selector:
        entity:
          domain:
            - sensor
          multiple: false
    day_normal_lux_level:
      name: Normal LUX level for day time
      description: >
        <br/>
        <br/>
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          step: 10
          unit_of_measurement: lx
          mode: slider
    night_normal_lux_level:
      name: Normal LUX level for night time
      description: >
        <br/>
        <br/>
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          step: 10
          unit_of_measurement: lx
          mode: slider

variables:
  lux_sensor: !input lux_sensor
  day_above_lux_level: "{{ !input day_above_lux_level | float }}"
  day_below_lux_level: "{{ day_above_lux_level + 1 }}"
  # night_above_lux_level: !input night_above_lux_level
  # night_below_lux_level: !input night_below_lux_level

trigger:
  - platform: numeric_state
    entity_id: !input lux_sensor
    above: "{{ day_above_lux_level }}"
    id: Light is on
  - platform: numeric_state
    entity_id: !input lux_sensor
    below: "{{ day_below }}"
    id: Light is off

action:
  - choose:
      - conditions:
          - condition: sun
            before: sunset
            after: sunrise
        sequence: []
      - conditions:
          - condition: sun
            before: sunrise
            after: sunset
        sequence: []
