blueprint:
  name: Car Tag Stable (0.1.6)
  homeassistant:
    min_version: 2024.5.0
  description: Car ESPHome Tag - Opens and Closes Garage Door
  domain: automation
  source_url: https://raw.githubusercontent.com/asucrews/ha-blueprints/main/automations/car_tag/car_tag.yaml
  input:
    bermuda_ble:
      selector:
        entity:
          integration: "bermuda"
          domain:
            - device_tracker
          multiple: false
    bermuda_ble_area:
      selector:
        entity:
          integration: "bermuda"
          domain:
            - sensor
          multiple: false
    bermuda_ble_areas:
      name: "Areas"
      description: >
        House Areas
      default:
        - "Garage"
    esphome_ble:
      selector:
        entity:
          domain:
            - binary_sensor
          multiple: false
    esphome_node_status:
      selector:
        entity:
          integration: "esphome"
          domain:
            - binary_sensor
          multiple: false
    garage_door_cover:
      name: Garage Door Cover
      description: Garage Door Cover?
      selector:
        entity:
          domain:
            - cover
          multiple: false
    garage_door_timer_helper:
      name: Garage Door Timer Helper
      description: Garage Door Timer Helper
      default: timer.none
      selector:
        entity:
          integration: "timer"
          domain:
            - timer
          multiple: false
    automation_trigger_id_helper:
      name: Automation Trigger ID
      description: Automation Trigger ID
      selector:
        entity:
          domain:
            - input_text
          multiple: false

variables:
  automation_trigger_id_helper: !input automation_trigger_id_helper
  bermuda_ble: !input bermuda_ble
  bermuda_ble_area: !input bermuda_ble_area
  bermuda_ble_areas: !input bermuda_ble_areas
  esphome_ble: !input esphome_ble
  esphome_node_status: !input esphome_node_status
  garage_door_cover: !input garage_door_cover
  garage_door_timer_helper: !input garage_door_timer_helper

trigger:
  - platform: state
    entity_id: !input bermuda_ble
    from: not_home
    to: home
    id: Bermuda BLE Found
  - platform: state
    entity_id: !input bermuda_ble
    from: home
    to: not_home
    id: Bermuda BLE Not Found
  - platform: state
    entity_id: !input esphome_ble
    from: "off"
    to: "on"
    id: ESPHome BLE Found
  - platform: state
    entity_id: !input esphome_ble
    from: "on"
    to: "off"
    id: ESPHome BLE Not Found
  - platform: state
    entity_id: !input esphome_node_status
    from: "off"
    to: "on"
    id: Connected
  - platform: state
    entity_id: !input esphome_node_status
    from: "on"
    to: "off"
    id: Disconnected

action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id: Connected
              - condition: template
                value_template: "{{ is_state(bermuda_ble_area, ['unknown','unavailable','off']) }}"
              - condition: template
                value_template: "{{ is_state(garage_door_cover, ['off', 'closed', 'closing']) }}"
        sequence:
          - service: cover.open_cover
            data: {}
            target:
              entity_id: !input garage_door_cover
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - Disconnected
              - condition: template
                value_template: "{{ is_state(bermuda_ble_area, ['unknown','unavailable','off']) }}"
              - condition: template
                value_template: "{{ is_state(garage_door_cover, ['on', 'open', 'opening']) }}"
        sequence:
          - if:
              - condition: state
                entity_id: !input garage_door_timer_helper
                state: active
            then:
              - service: timer.cancel
                target:
                  entity_id: !input garage_door_timer_helper
                data: {}
              - service: timer.start
                metadata: {}
                data: {}
                target:
                  entity_id: !input garage_door_timer_helper
            else:
              - service: timer.start
                metadata: {}
                data: {}
                target:
                  entity_id: !input garage_door_timer_helper
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - Bermuda BLE Found
                  - ESPHome BLE Found
              - condition: template
                value_template: "{{ is_state(garage_door_cover, ['off', 'closed', 'closing']) }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ len(bermuda_ble_areas) > 0 }}"
            then:
              - condition: template
                value_template: "{{ is_state(bermuda_ble_area, bermuda_ble_areas) }}"
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 5
                  milliseconds: 0
              - service: cover.open_cover
                data: {}
                target:
                  entity_id: !input garage_door_cover
            else:
              - service: cover.open_cover
                data: {}
                target:
                  entity_id: !input garage_door_cover
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - Bermuda BLE Not Found
                  - ESPHome BLE Not Found
              - condition: template
                value_template: "{{ is_state(garage_door_cover, ['on', 'open', 'opening']) }}"
        sequence:
          - if:
              - condition: state
                entity_id: !input garage_door_timer_helper
                state: active
            then:
              - service: timer.cancel
                target:
                  entity_id: !input garage_door_timer_helper
                data: {}
              - service: timer.start
                metadata: {}
                data: {}
                target:
                  entity_id: !input garage_door_timer_helper
            else:
              - service: timer.start
                metadata: {}
                data: {}
                target:
                  entity_id: !input garage_door_timer_helper
  - service: input_text.set_value
    target:
      entity_id: !input automation_trigger_id_helper
    data:
      value: "{{ trigger.id }}"

mode: queued
max: 5
