blueprint:
  name: Car Presence ESPHome (0.1.0rc1)
  homeassistant:
    min_version: 2024.4.0
  description: >
    <br/>
    <br/>
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/car_presence_esphome/car_presence_esphome.yaml
  input:
    esphome_device:
      name: Lock
      description: Lock
      selector:
        integration: esphome
        entity:
          domain:
            - binary_sensor
          multiple: false

variables:
  esphome_device: !input esphome_device

trigger: []

action: []
