blueprint:
  name: Smaert Vents - Flair (0.1.0)
  description: >
    Perform actions on various scenes supported by the Inovelli Inovelli Smart Dimmer FKA 2-1 Switch<br/>
    <br/>
    Note that the x2, x3, x4, x5 variants DO NOT work if you have put your switch in 'Instant On' mode.<br/>
    <br/>
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/inovelli/red/smart_dimmer/smart_dimmer.yaml
  input:
    detection_mode:
      name: Detection Mode
      description: >
        Does the room or area have only a door sensor or an occupancy helper? An occupancy helper is an input boolean used to track if a room is occupied. In most cases, multiple automations or scripts will track room occupancy. A helper makes it easier because you only need one place, versus many, to track this.<br/>
        <br/>Options:<br/>
          - Room Occupancy: Automation utilizes an occupancy helper to track if the room is occupied. This option simplifies tracking room occupancy by consolidating it into one place.<br/>
          - Door Sensor: Automation relies solely on a door sensor to determine occupancy. This option does not utilize an occupancy helper, requiring individual automations or scripts to track room occupancy.<br/>
        <br/>Default value: Door Sensor Only.<br/>
      default: door_sensor
      selector:
        select:
          mode: dropdown
          options:
          - label: Room Occupancy
            value: room_occupancy
          - label: Door Sensor
            value: door_sensor
          custom_value: false
          multiple: false
          sort: false
    door_sensor:
      name: Door Sensor or Door Sensor Group
      description: >
        Select the door sensor or group of door sensors.<br/>
        <br/>Please note: This input is restricted to entities within the binary_sensor domain and allows only a single selection.  This field and this input is required.<br/>
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    door_sensor_open_delay:
      name: Door Sensor Open Delay (Optional)
      description: >
        Specify the delay time, in seconds, for the door sensor to register an open event after detecting movement.  This option helps reduce false events triggered by activities like door openings and closings or shared spaces with multiple occupants.<br/>
        <br/>Default value: 0 seconds, Min value: 0 seconds, and Max value: 60 seconds. Only adjust if you require a delay for the door sensor open event and this input is optional.<br/>
      default: 0
      selector:
        number:
          mode: box
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          step: 1.0
    door_sensor_close_delay:
      name: Door Sensor Close Delay (Optional)
      description: >
        Specify the delay time, in seconds, for the door sensor to register a close event after detecting no movement.  This option helps reduce false events triggered by activities like door openings and closings or shared spaces with multiple occupants.<br/>
        <br/>Default value: 0 seconds, Min value: 0 seconds, and Max value: 60 seconds. Only adjust if you require a delay for the door sensor close event and this input is optional.<br/>
      default: 0
      selector:
        number:
          mode: box
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          step: 1.0
    flair_activity_status:
      name: Flair Activity Status
      description: Flair Activity Status
      selector:
        entity:
          domain:
          - input_select
          multiple: false        
    flair_clear_hold:
      name: Flair Clear Hold Button
      description: Flair Clear Hold Button
      selector:
        entity:
          domain:
          - button
          multiple: false  
    ecobee_smart_sensor_occupancy:
      name: Ecobee Smaer Sensor Occupancy
      description: Ecobee Smaer Sensor Occupancy
      default: 'binary_sensor.none'
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    room_occupancy_helper:
      name: Room Occupancy Helper (Optional)
      description: >
        Select an input boolean entity to serve as an occupancy helper within the designated area ("box").  To utilize this function, create an input_boolean helper entity in your Home Assistant configuration or UI.<br/>
        The occupancy helper can be used to track the overall occupancy status and coordinate actions based on occupancy detection.  Can be utilized for more advanced automation scenarios where additional logic based on occupancy status is required.<br/>
        <br/>Default value: 'input_boolean.none'. Only change if you intend to use this field and this input is optional.<br/>
      default: 'input_boolean.none'
      selector:
        entity:
          domain:
          - input_boolean
          multiple: false

variables:
  door_sensor: !input door_sensor
  door_sensor_open_delay: !input door_sensor_open_delay
  door_sensor_close_delay: !input door_sensor_close_delay
  flair_activity_status: !input flair_activity_status
  flair_clear_hold: !input flair_clear_hold
  hvac_smart_sensor_occupancy: !input ecobee_smart_sensor_occupancy
  room_occupancy_helper: !input room_occupancy_helper

trigger:
  # If door is opened
  - platform: state
    entity_id: >
      {% if detection_mode == 'door_sensor' %}
        !input door_sensor
      {% elif detection_mode == 'room_occupancy' %}
        !input room_occupancy_helper
      {% endif %}
    from: "off"
    to: "on"
    id: Room Occupied
    for: >
      {% if detection_mode == 'door_sensor' %}
        !input door_sensor_open_delay
      {% elif detection_mode == 'room_occupancy' %}
        0
      {% endif %}
  # If door is closed
  - platform: state
    entity_id: >
      {% if detection_mode == 'door_sensor' %}
        !input door_sensor
      {% elif detection_mode == 'room_occupancy' %}
        !input room_occupancy_helper
      {% endif %}
    from: "on"
    to: "off"
    id: Room Unoccupied
    for: >
      {% if detection_mode == 'door_sensor' %}
        !input door_sensor_close_delay
      {% elif detection_mode == 'room_occupancy' %}
        0
      {% endif %}
  # HVAC Remote Occupancy Sensor is detected 
  - platform: state
    entity_id: !input ecobee_smart_sensor_occupancy
    from: "off"
    to: "on"
    id: HVAC Occupied
  # HVAC Remote Occupancy Sensor is clear  
  - platform: state
    entity_id: !input ecobee_smart_sensor_occupancy
    from: "on"
    to: "off"
    id: HVAC Unoccupied

action:
  - choose:
      - conditions:
          - condition: and
            conditions:
            - condition: trigger
              id:
                - Room Occupied
        sequence:
          - service: select.select_option
            data:
              option: Active
            target:
              entity_id: !input flair_activity_status
          - service: button.press
            data: {}
            target:
              entity_id: !input flair_clear_hold
      - conditions:
          - condition: and
            conditions:
            - condition: trigger
              id:
                - Room Unoccupied
        sequence:
          - service: select.select_option
            data:
              option: Active
            target:
              entity_id: !input flair_activity_status
          - service: button.press
            data: {}
            target:
              entity_id: !input flair_clear_hold
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - HVAC Occupied
              - condition: state
                entity_id: !input door_sensor
                state: Window/door is open
        sequence:
          - service: select.select_option
            data:
              option: Active
            target:
              entity_id: !input flair_activity_status
          - service: button.press
            data: {}
            target:
              entity_id: !input flair_clear_hold
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - HVAC Unoccupied
              - condition: state
                entity_id: !input door_sensor
                state: Window/door is open
        sequence:
          - service: select.select_option
            data:
              option: Inactive
            target:
              entity_id: !input flair_activity_status
          - service: button.press
            data: {}
            target:
              entity_id: !input flair_clear_hold 