blueprint:
  name: Log Door Open Time
  description: >
    Updates an input_datetime whenever the selected door sensor opens.
  domain: automation
  input:
    door_sensor:
      name: Door Sensor
      selector:
        entity:
          domain: binary_sensor
    door_open_time:
      name: Input Datetime for Last Door Open
      selector:
        entity:
          domain: input_datetime

trigger:
  - platform: state
    entity_id: !input door_sensor
    to: "on"

action:
  - action: input_datetime.set_datetime
    target:
      entity_id: !input door_open_time
    data:
      timestamp: "{{ now().timestamp() }}"
