blueprint:
  homeassistant:
    min_version: 2026.2.0
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/blueprints/automation/vacuum_job_manager/v1/vacuum_job_manager.yaml
  name: Vacuum Job Manager (iRobot) v1.1 - WITB Override + Lights
  description: >
    Roomba-safe job manager. Does NOT treat 'docked' as complete.
    Completes only when mission counters increment (successful/failed/canceled).
    v1.1: turn ON lights/switches + enable WITB automation_override booleans during job;
    on job end, disable overrides and turn OFF lights if NOT occupied.

  input:
    vacuum_entity:
      name: Vacuum Entity
      selector:
        entity:
          domain: vacuum

    enabled_boolean:
      name: Enabled helper
      selector: { entity: { domain: input_boolean } }

    requested_boolean:
      name: Requested helper
      selector: { entity: { domain: input_boolean } }

    active_boolean:
      name: Active helper
      selector: { entity: { domain: input_boolean } }

    error_boolean:
      name: Error helper
      selector: { entity: { domain: input_boolean } }

    phase_select:
      name: Phase helper
      selector: { entity: { domain: input_select } }

    last_start_datetime:
      name: Last start helper
      selector: { entity: { domain: input_datetime } }

    last_end_datetime:
      name: Last end helper
      selector: { entity: { domain: input_datetime } }

    failures_counter:
      name: Failures counter
      selector: { entity: { domain: counter } }

    watchdog_timer:
      name: Watchdog timer
      selector: { entity: { domain: timer } }

    max_runtime_min:
      name: Max runtime (minutes)
      selector: { entity: { domain: input_number } }

    request_button:
      name: Request Run button
      selector: { entity: { domain: input_button } }

    # Schedule
    use_schedule:
      name: Enable schedule
      default: false
      selector: { boolean: {} }

    schedule_time:
      name: Schedule time
      default: "10:00:00"
      selector: { time: {} }

    schedule_days:
      name: Schedule days
      default: [mon, tue, wed, thu, fri]
      selector:
        select:
          multiple: true
          options:
            - { label: Monday, value: mon }
            - { label: Tuesday, value: tue }
            - { label: Wednesday, value: wed }
            - { label: Thursday, value: thu }
            - { label: Friday, value: fri }
            - { label: Saturday, value: sat }
            - { label: Sunday, value: sun }

    notify_service:
      name: Notify service (optional)
      default: ""
      selector: { text: {} }

    # iRobot mission sensors
    successful_missions_sensor:
      name: Successful missions sensor
      selector: { entity: { domain: sensor } }

    failed_missions_sensor:
      name: Failed missions sensor
      selector: { entity: { domain: sensor } }

    canceled_missions_sensor:
      name: Canceled missions sensor
      selector: { entity: { domain: sensor } }

    # Baseline helpers (input_number)
    base_successful_input:
      name: Baseline successful helper
      selector: { entity: { domain: input_number } }

    base_failed_input:
      name: Baseline failed helper
      selector: { entity: { domain: input_number } }

    base_canceled_input:
      name: Baseline canceled helper
      selector: { entity: { domain: input_number } }

    # v1.1: lights/switches to force ON during job
    vacuum_lighting_entities:
      name: Lights / switches to turn ON during job
      default: []
      selector:
        entity:
          multiple: true

    # v1.1: WITB automation_override booleans (locks)
    witb_automation_override_booleans:
      name: WITB automation_override booleans to enable during job
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true

    # v1.1: occupancy entities gate (if ANY on, do not turn lights off at job end)
    occupancy_entities:
      name: Occupancy entities (rooms/area)
      default: []
      selector:
        entity:
          multiple: true

mode: queued
max: 10

variables:
  notify: !input notify_service

  s_success: !input successful_missions_sensor
  s_failed: !input failed_missions_sensor
  s_canceled: !input canceled_missions_sensor

  b_success: !input base_successful_input
  b_failed: !input base_failed_input
  b_canceled: !input base_canceled_input

  max_runtime: !input max_runtime_min

  lights_targets: !input vacuum_lighting_entities
  overrides: !input witb_automation_override_booleans
  occ_ents: !input occupancy_entities

trigger:
  - id: button_request
    platform: state
    entity_id: !input request_button

  - id: schedule_request
    platform: time
    at: !input schedule_time
    enabled: !input use_schedule

  # IMPORTANT: this makes button->request->start reliable
  - id: requested_on
    platform: state
    entity_id: !input requested_boolean
    to: "on"

  - id: vacuum_state
    platform: state
    entity_id: !input vacuum_entity

  - id: watchdog_done
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input watchdog_timer

  - id: success_changed
    platform: state
    entity_id: !input successful_missions_sensor

  - id: failed_changed
    platform: state
    entity_id: !input failed_missions_sensor

  - id: canceled_changed
    platform: state
    entity_id: !input canceled_missions_sensor

action:
  # 1) Requests / watchdog / completion
  - choose:

      # Button request -> queue
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'button_request' }}"
          - condition: state
            entity_id: !input active_boolean
            state: "off"
        sequence:
          - service: input_boolean.turn_on
            target: { entity_id: !input requested_boolean }
          - service: input_select.select_option
            target: { entity_id: !input phase_select }
            data: { option: queued }

      # Schedule request -> queue
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'schedule_request' }}"
          - condition: time
            weekday: !input schedule_days
          - condition: state
            entity_id: !input enabled_boolean
            state: "on"
          - condition: state
            entity_id: !input active_boolean
            state: "off"
        sequence:
          - service: input_boolean.turn_on
            target: { entity_id: !input requested_boolean }
          - service: input_select.select_option
            target: { entity_id: !input phase_select }
            data: { option: queued }

      # Watchdog -> return to base (does NOT end job)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'watchdog_done' }}"
          - condition: state
            entity_id: !input active_boolean
            state: "on"
        sequence:
          - service: vacuum.return_to_base
            target: { entity_id: !input vacuum_entity }
          - choose:
              - conditions: "{{ notify != '' }}"
                sequence:
                  - service: "{{ notify }}"
                    data:
                      title: "Vacuum watchdog"
                      message: >
                        Max runtime exceeded ({{ states(max_runtime) | int }} min). Sent return_to_base.

      # Mission counters changed -> true end (recharge-safe)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['success_changed','failed_changed','canceled_changed'] }}"
          - condition: state
            entity_id: !input active_boolean
            state: "on"
        sequence:
          - variables:
              base_s: "{{ states(b_success) | int(0) }}"
              base_f: "{{ states(b_failed) | int(0) }}"
              base_c: "{{ states(b_canceled) | int(0) }}"
              now_s: "{{ states(s_success) | int(0) }}"
              now_f: "{{ states(s_failed) | int(0) }}"
              now_c: "{{ states(s_canceled) | int(0) }}"
              any_occ_on: "{{ expand(occ_ents) | selectattr('state','eq','on') | list | length > 0 }}"
              overrides_ids: "{{ overrides | join(',') }}"
              lights_ids: "{{ lights_targets | join(',') }}"
          - choose:

              # Failed -> error
              - conditions: "{{ now_f > base_f }}"
                sequence:
                  - service: timer.cancel
                    target: { entity_id: !input watchdog_timer }

                  # unlock overrides
                  - choose:
                      - conditions: "{{ overrides | length > 0 }}"
                        sequence:
                          - service: input_boolean.turn_off
                            target:
                              entity_id: "{{ overrides_ids }}"
                            continue_on_error: true

                  # lights off only if not occupied
                  - choose:
                      - conditions: "{{ (lights_targets | length > 0) and (not any_occ_on) }}"
                        sequence:
                          - service: homeassistant.turn_off
                            target:
                              entity_id: "{{ lights_ids }}"
                            continue_on_error: true

                  - service: input_boolean.turn_on
                    target: { entity_id: !input error_boolean }
                  - service: counter.increment
                    target: { entity_id: !input failures_counter }
                  - service: input_boolean.turn_off
                    target: { entity_id: !input active_boolean }
                  - service: input_boolean.turn_off
                    target: { entity_id: !input requested_boolean }
                  - service: input_select.select_option
                    target: { entity_id: !input phase_select }
                    data: { option: error }
                  - service: input_datetime.set_datetime
                    target: { entity_id: !input last_end_datetime }
                    data:
                      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

              # Canceled -> canceled (count as failure)
              - conditions: "{{ now_c > base_c }}"
                sequence:
                  - service: timer.cancel
                    target: { entity_id: !input watchdog_timer }

                  - choose:
                      - conditions: "{{ overrides | length > 0 }}"
                        sequence:
                          - service: input_boolean.turn_off
                            target:
                              entity_id: "{{ overrides_ids }}"
                            continue_on_error: true

                  - choose:
                      - conditions: "{{ (lights_targets | length > 0) and (not any_occ_on) }}"
                        sequence:
                          - service: homeassistant.turn_off
                            target:
                              entity_id: "{{ lights_ids }}"
                            continue_on_error: true

                  - service: counter.increment
                    target: { entity_id: !input failures_counter }
                  - service: input_boolean.turn_off
                    target: { entity_id: !input active_boolean }
                  - service: input_boolean.turn_off
                    target: { entity_id: !input requested_boolean }
                  - service: input_select.select_option
                    target: { entity_id: !input phase_select }
                    data: { option: canceled }
                  - service: input_datetime.set_datetime
                    target: { entity_id: !input last_end_datetime }
                    data:
                      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

              # Successful -> completed
              - conditions: "{{ now_s > base_s }}"
                sequence:
                  - service: timer.cancel
                    target: { entity_id: !input watchdog_timer }

                  - choose:
                      - conditions: "{{ overrides | length > 0 }}"
                        sequence:
                          - service: input_boolean.turn_off
                            target:
                              entity_id: "{{ overrides_ids }}"
                            continue_on_error: true

                  - choose:
                      - conditions: "{{ (lights_targets | length > 0) and (not any_occ_on) }}"
                        sequence:
                          - service: homeassistant.turn_off
                            target:
                              entity_id: "{{ lights_ids }}"
                            continue_on_error: true

                  - service: input_boolean.turn_off
                    target: { entity_id: !input active_boolean }
                  - service: input_boolean.turn_off
                    target: { entity_id: !input requested_boolean }
                  - service: input_select.select_option
                    target: { entity_id: !input phase_select }
                    data: { option: completed }
                  - service: input_datetime.set_datetime
                    target: { entity_id: !input last_end_datetime }
                    data:
                      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

    default: []

  # 2) Start when requested + ready (runs on any trigger, including requested_on)
  - choose:
      - conditions:
          - condition: state
            entity_id: !input enabled_boolean
            state: "on"
          - condition: state
            entity_id: !input requested_boolean
            state: "on"
          - condition: state
            entity_id: !input active_boolean
            state: "off"
          - condition: state
            entity_id: !input vacuum_entity
            state: "docked"
        sequence:
          - variables:
              overrides_ids: "{{ overrides | join(',') }}"
              lights_ids: "{{ lights_targets | join(',') }}"

          # enable overrides + lights ON
          - choose:
              - conditions: "{{ overrides | length > 0 }}"
                sequence:
                  - service: input_boolean.turn_on
                    target:
                      entity_id: "{{ overrides_ids }}"
                    continue_on_error: true

          - choose:
              - conditions: "{{ lights_targets | length > 0 }}"
                sequence:
                  - service: homeassistant.turn_on
                    target:
                      entity_id: "{{ lights_ids }}"
                    continue_on_error: true

          # snapshot baselines
          - service: input_number.set_value
            target: { entity_id: !input base_successful_input }
            data: { value: "{{ states(s_success) | int(0) }}" }
          - service: input_number.set_value
            target: { entity_id: !input base_failed_input }
            data: { value: "{{ states(s_failed) | int(0) }}" }
          - service: input_number.set_value
            target: { entity_id: !input base_canceled_input }
            data: { value: "{{ states(s_canceled) | int(0) }}" }

          - service: input_boolean.turn_on
            target: { entity_id: !input active_boolean }
          - service: input_boolean.turn_off
            target: { entity_id: !input error_boolean }
          - service: input_select.select_option
            target: { entity_id: !input phase_select }
            data: { option: cleaning }
          - service: input_datetime.set_datetime
            target: { entity_id: !input last_start_datetime }
            data:
              datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
          - service: timer.start
            target: { entity_id: !input watchdog_timer }
            data:
              duration: "{{ (states(max_runtime) | int(240) * 60) | int }}"
          - service: vacuum.start
            target: { entity_id: !input vacuum_entity }
    default: []

  # 3) Phase mapping while job active/requested
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'vacuum_state' }}"
          - condition: or
            conditions:
              - condition: state
                entity_id: !input active_boolean
                state: "on"
              - condition: state
                entity_id: !input requested_boolean
                state: "on"
        sequence:
          - variables:
              st: "{{ trigger.to_state.state }}"
          - choose:
              - conditions: "{{ st == 'cleaning' }}"
                sequence:
                  - service: input_select.select_option
                    target: { entity_id: !input phase_select }
                    data: { option: cleaning }
              - conditions: "{{ st in ['paused','idle'] }}"
                sequence:
                  - service: input_select.select_option
                    target: { entity_id: !input phase_select }
                    data: { option: paused }
              - conditions: "{{ st == 'returning' }}"
                sequence:
                  - service: input_select.select_option
                    target: { entity_id: !input phase_select }
                    data: { option: returning }
              - conditions: "{{ st == 'docked' }}"
                sequence:
                  - service: input_select.select_option
                    target: { entity_id: !input phase_select }
                    data: { option: docked }
              - conditions: "{{ st in ['unavailable','unknown'] }}"
                sequence:
                  - service: input_select.select_option
                    target: { entity_id: !input phase_select }
                    data: { option: "{{ st }}" }
    default: []
