blueprint:
  name: WITB+ Dev Occupancy (1.0.0)
  homeassistant:
    min_version: 2025.6.0
  description: >
    Basic occupancy detection using the "Wasp in the Box" concept. Marks the room
    as occupied when motion is detected, and clears it when the door opens without
    motion or motion clears while the door is open. Assumes the room stays occupied
    while the door is closed and no new motion has been detected.
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/witb_plus/dev/witb_plus_occupancy.yaml

  input:
    sensor_entities:
      name: Sensor Entities
      description: Required motion and door sensors used to track occupancy.
      collapsed: true
      input:
        door_sensor:
          name: Door Sensor
          description: >
            The binary_sensor representing the door to the room ("box").
            Required for tracking entry and exit.
          selector:
            entity:
              domain: binary_sensor
              multiple: false
        motion_sensor:
          name: Motion Sensor
          description: >
            The binary_sensor detecting movement within the room ("box").
            Required for identifying presence.
          selector:
            entity:
              domain: binary_sensor
              multiple: false

    sensor_options:
      name: Sensor Options
      description: Optional delay settings for sensor state changes.
      collapsed: true
      input:
        door_sensor_open_delay:
          name: Door Open Delay
          description: Delay (in seconds) before triggering on door open.
          default: 1
          selector:
            number:
              mode: box
              min: 0.0
              max: 60.0
              step: 1.0
              unit_of_measurement: seconds

        door_sensor_close_delay:
          name: Door Close Delay
          description: Delay (in seconds) before triggering on door close.
          default: 1
          selector:
            number:
              mode: box
              min: 0.0
              max: 60.0
              step: 1.0
              unit_of_measurement: seconds

        motion_sensor_delay:
          name: Motion Off Delay
          description: Delay (in seconds) before triggering on motion cleared.
          default: 30
          selector:
            number:
              mode: box
              min: 0.0
              max: 3600.0
              step: 1.0
              unit_of_measurement: seconds

    occupancy_options:
      name: Occupancy Options
      description: Configure the input_boolean helper used to track occupancy state.
      collapsed: true
      input:
        occupancy_helper:
          name: Occupancy Helper
          description: >
            An input_boolean to store the room's occupancy state.
            Create one in your Helpers UI before selecting.
          selector:
            entity:
              domain: input_boolean
              multiple: false

variables:
  door_sensor: !input door_sensor
  door_sensor_entity_id: "{{ door_sensor if door_sensor is defined and door_sensor else 'binary_sensor.none' }}"
  door_sensor_open_delay: !input door_sensor_open_delay
  door_sensor_close_delay: !input door_sensor_close_delay
  motion_sensor: !input motion_sensor
  motion_sensor_entity_id: "{{ motion_sensor if motion_sensor is defined and motion_sensor else 'binary_sensor.none' }}"
  motion_sensor_delay: !input motion_sensor_delay
  occupancy_helper: !input occupancy_helper
  occupancy_helper_entity_id: "{{ occupancy_helper if occupancy_helper is defined and occupancy_helper else 'input_boolean.none' }}"
  bypass_helper: !input bypass_helper
  bypass_helper_entity_id: "{{ bypass_helper if bypass_helper is defined and bypass_helper else 'input_boolean.none' }}"

trigger:
  - platform: state
    entity_id: !input door_sensor
    from: 'off'
    to: 'on'
    id: Door Opened
    for: !input door_sensor_open_delay

  - platform: state
    entity_id: !input door_sensor
    from: 'on'
    to: 'off'
    id: Door Closed
    for: !input door_sensor_close_delay

  - platform: state
    entity_id: !input motion_sensor
    from: 'off'
    to: 'on'
    id: Motion On

  - platform: state
    entity_id: !input motion_sensor
    from: 'on'
    to: 'off'
    id: Motion Off
    for: !input motion_sensor_delay

condition:
  condi

action:
  - choose:
      - conditions:
          - alias: Door just closed
            condition: trigger
            id: Door Closed
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input occupancy_helper

      - conditions:
          - alias: Door opened with no motion
            condition: trigger
            id: Door Opened
          - alias: No motion active
            condition: state
            entity_id: !input motion_sensor
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input occupancy_helper

      - conditions:
          - alias: Motion detected
            condition: trigger
            id: Motion On
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input occupancy_helper

      - conditions:
          - alias: Motion cleared while door is open
            condition: trigger
            id: Motion Off
          - alias: Door is open
            condition: state
            entity_id: !input door_sensor
            state: 'on'
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input occupancy_helper

mode: single
