blueprint:
  name: WITB+ Dev Occupancy (1.0.0)
  homeassistant:
    min_version: 2024.12.0
  description: >
    **WITB+ (Wasp in the Box Plus)** is an advanced occupancy detection automation, inspired by the "Wasp in the Box" concept. 
    It intelligently determines occupancy status using a combination of motion and door sensors, ensuring precise room presence detection.

    This blueprint generates a virtual occupancy sensor based on sensor inputs, allowing seamless automation of smart devices such as lights, 
    switches, and fans based on whether a room is occupied.

    ### **Key Features:**
    - **Accurate Occupancy Detection:** Uses motion and door sensors to track room presence dynamically.
    - **Smart Automation Integration:** Automate lights, switches, and fans based on occupancy status.
    - **Configurable Delays:** Adjustable settings to fine-tune sensor response times and reduce false positives.
    - **Bypass Functionality:** Supports manual overrides via input_boolean helpers.
    - **Minimal Configuration:** Simple setup requiring only a few sensors and an occupancy tracking helper.

  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/witb_plus/dev/witb_plus_occupancy.yaml

  input:
    sensor_entities:
      name: Sensor Entities
      description: >
        Select the motion and door sensors that will be used to determine room occupancy.
      collapsed: true
      input:
        door_sensor:
          name: Door Sensor
          description: >
            Select the **binary sensor** that represents the main door(s) to the monitored space.
            This sensor detects when the door opens or closes, helping determine if someone has entered or exited.

            **Requirements:**
            - Must be a `binary_sensor`.
            - Supports only a single selection.
          selector:
            entity:
              domain: binary_sensor
              multiple: false

        motion_sensor:
          name: Motion Sensor
          description: >
            Select the **binary sensor** responsible for detecting movement inside the monitored space.
            Motion activity helps determine when someone is present.

            **Requirements:**
            - Must be a `binary_sensor`.
            - Supports only a single selection.
          selector:
            entity:
              domain: binary_sensor
              multiple: false

    sensor_options:
      name: Sensor Configuration
      description: >
        Fine-tune sensor behavior by adding delays to prevent false triggers.
      collapsed: true
      input:
        door_sensor_open_delay:
          name: Door Open Detection Delay
          description: >
            Set a delay (in seconds) before detecting a **door open** event.
            This helps filter out brief, accidental door movements that should not impact occupancy status.

            **Defaults:** `1s` (Min: `0s`, Max: `60s`)
          default: 1
          selector:
            number:
              mode: box
              min: 0
              max: 60
              unit_of_measurement: seconds
              step: 1

        door_sensor_close_delay:
          name: Door Close Detection Delay
          description: >
            Set a delay (in seconds) before detecting a **door close** event.
            Useful for reducing unintended occupancy state changes in high-traffic areas.

            **Defaults:** `1s` (Min: `0s`, Max: `60s`)
          default: 1
          selector:
            number:
              mode: box
              min: 0
              max: 60
              unit_of_measurement: seconds
              step: 1

        motion_sensor_delay:
          name: Motion Sensor Clear Delay
          description: >
            Set the delay (in seconds) before the motion sensor registers **no movement**.
            Helps prevent premature occupancy clearance when someone is still inside but motionless.

            **Defaults:** `30s` (Min: `0s`, Max: `3600s`)
          default: 30
          selector:
            number:
              mode: box
              min: 0
              max: 3600
              unit_of_measurement: seconds
              step: 1

    occupancy_options:
      name: Occupancy Tracking
      description: >
        Configure how the blueprint tracks room occupancy.
      collapsed: true
      input:
        occupancy_helper:
          name: Occupancy Status Helper
          description: >
            Select an **input_boolean** entity to act as an occupancy tracker.
            This entity will store the room's occupancy state (`on` = occupied, `off` = unoccupied).

            **Requirement:** The selected entity must be manually created in Home Assistant.
          selector:
            entity:
              domain: input_boolean
              multiple: false

variables:
  door_sensor: !input door_sensor
  door_sensor_open_delay: !input door_sensor_open_delay
  door_sensor_close_delay: !input door_sensor_close_delay
  motion_sensor: !input motion_sensor
  motion_sensor_delay: !input motion_sensor_delay
  occupancy_helper: !input occupancy_helper

trigger:
  - platform: state
    entity_id: !input door_sensor
    from: "off"
    to: "on"
    id: Door Opened
    for: !input door_sensor_open_delay

  - platform: state
    entity_id: !input door_sensor
    from: "on"
    to: "off"
    id: Door Closed
    for: !input door_sensor_close_delay

  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
    id: Motion Detected

  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    id: No Motion
    for: !input motion_sensor_delay

action:
  - choose:
      - conditions:
          - condition: trigger
            id: Door Closed
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input occupancy_helper

      - conditions:
          - condition: trigger
            id: Door Opened
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input occupancy_helper

      - conditions:
          - condition: trigger
            id: Motion Detected
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input occupancy_helper

      - conditions:
          - condition: trigger
            id: No Motion
          - condition: state
            entity_id: !input door_sensor
            state: "on"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input occupancy_helper

mode: single
max_exceeded: silent
