blueprint:
  name: WITB+ Merge Occupancy (1.1.2)
  description: >
    Advanced occupancy detection blueprint based on the Wasp-In-The-Box principle.
    Combines motion and door sensors with smart timestamp logic to detect and clear room presence accurately.

  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/witb_plus/dev/witb_plus_merge.yaml
  homeassistant:
    min_version: 2024.12.0

  input:
    sensor_entities:
      name: Sensor Entities
      input:
        door_sensor:
          name: Door Sensor
          selector:
            entity:
              domain: binary_sensor
        motion_sensor:
          name: Motion Sensor
          selector:
            entity:
              domain: binary_sensor

    sensor_options:
      name: Sensor Options
      input:
        door_sensor_open_delay:
          name: Door Open Delay
          default: 1
          selector:
            number:
              min: 0
              max: 60
              unit_of_measurement: seconds
        door_sensor_close_delay:
          name: Door Close Delay
          default: 1
          selector:
            number:
              min: 0
              max: 60
              unit_of_measurement: seconds
        motion_sensor_delay:
          name: Motion Clear Delay
          default: 30
          selector:
            number:
              min: 0
              max: 3600
              unit_of_measurement: seconds

    occupancy_options:
      name: Occupancy Logic
      input:
        occupancy_helper:
          name: Occupancy Helper (input_boolean)
          selector:
            entity:
              domain: input_boolean
        last_motion_helper:
          name: Last Motion Timestamp (input_datetime)
          selector:
            entity:
              domain: input_datetime
        bypass_helper:
          name: Bypass Occupancy (Optional)
          default: null
          selector:
            entity:
              domain: input_boolean

    advanced_logic:
      name: Advanced Behavior Options
      input:
        enable_reset_on_door_close:
          name: Clear occupancy on door close after delay
          default: true
          selector:
            boolean:
        enable_clear_when_door_open_and_idle:
          name: Clear occupancy if door left open with no motion
          default: true
          selector:
            boolean:
        enable_smart_timestamp_clear:
          name: Use timestamp logic for smart clearance
          default: true
          selector:
            boolean:
        reset_on_door_close_min_seconds:
          name: Min time before reset on door close
          default: 20
          selector:
            number:
              min: 1
              max: 600
              unit_of_measurement: seconds
        bypass_timeout_minutes:
          name: Auto-disable bypass (minutes, 0 = never)
          default: 0
          selector:
            number:
              min: 0
              max: 360
        recheck_on_start:
          name: Sync state on Home Assistant restart
          default: true
          selector:
            boolean:

variables:
  door_sensor: !input door_sensor
  door_sensor_entity_id: "{{ door_sensor if door_sensor is defined and door_sensor else 'binary_sensor.none' }}"
  motion_sensor: !input motion_sensor
  motion_sensor_entity_id: "{{ motion_sensor if motion_sensor is defined and motion_sensor else 'binary_sensor.none' }}"
  occupancy_helper: !input occupancy_helper
  occupancy_helper_entity_id: "{{ occupancy_helper if occupancy_helper is defined and occupancy_helper else 'input_boolean.none' }}"
  last_motion_helper: !input last_motion_helper
  last_motion_helper_entity_id: "{{ last_motion_helper if last_motion_helper is defined and last_motion_helper else 'input_datetime.none' }}"
  bypass_helper: !input bypass_helper
  bypass_helper_entity_id: "{{ bypass_helper if bypass_helper is defined and bypass_helper else 'input_boolean.none' }}"
  door_sensor_open_delay: !input door_sensor_open_delay
  door_sensor_close_delay: !input door_sensor_close_delay
  motion_sensor_delay: !input motion_sensor_delay
  enable_reset_on_door_close: !input enable_reset_on_door_close
  enable_clear_when_door_open_and_idle: !input enable_clear_when_door_open_and_idle
  enable_smart_timestamp_clear: !input enable_smart_timestamp_clear
  bypass_timeout_minutes: !input bypass_timeout_minutes
  recheck_on_start: !input recheck_on_start
  reset_on_door_close_min_seconds: !input reset_on_door_close_min_seconds

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
    id: motion_detected
  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for: !input motion_sensor_delay
    id: motion_cleared
  - platform: state
    entity_id: !input door_sensor
    from: "off"
    to: "on"
    for: !input door_sensor_open_delay
    id: door_opened
  - platform: state
    entity_id: !input door_sensor
    from: "on"
    to: "off"
    for: !input door_sensor_close_delay
    id: door_closed
  - platform: homeassistant
    event: start
    id: ha_start
  - platform: state
    entity_id: !input door_sensor
    to: "on"
    for:
      seconds: 15
    id: door_left_open

condition:
  - condition: template
    value_template: >-
      {{ bypass_helper_entity_id != 'binary_sensor.none' and is_state(bypass_helper_entity_id, 'off') }}

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_detected
        sequence:
          - service: input_datetime.set_datetime
            data:
              timestamp: "{{ now().timestamp() }}"
            target:
              entity_id: "{{ last_motion_helper_entity_id }}"
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ occupancy_helper_entity_id }}"

      - conditions:
          - condition: trigger
            id: motion_cleared
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ is_state(door_sensor, 'on') }}
                sequence:
                  - service: input_boolean.turn_off
                    target:
                      entity_id: "{{ occupancy_helper_entity_id }}"
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ enable_smart_timestamp_clear and is_state(door_sensor, 'off') and
                         as_timestamp(states[door_sensor_entity_id].last_changed) > as_timestamp(states[last_motion_helper_entity_id].state) }}
                sequence:
                  - service: input_boolean.turn_off
                    target:
                      entity_id: "{{ occupancy_helper_entity_id }}"

      - conditions:
          - condition: trigger
            id: door_opened
          - condition: state
            entity_id: "{{ motion_sensor_entity_id }}"
            state: "off"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ occupancy_helper_entity_id }}"

      - conditions:
          - condition: trigger
            id: door_closed
          - condition: template
            value_template: >-
              {{ enable_reset_on_door_close and
              (now().timestamp() - states[occupancy_helper_entity_id].last_changed.timestamp()) > reset_on_door_close_min_seconds }}
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ occupancy_helper_entity_id }}"

      - conditions:
          - condition: trigger
            id: door_left_open
          - condition: template
            value_template: >-
              {{ enable_clear_when_door_open_and_idle and is_state(motion_sensor, 'off') and
                 as_timestamp(states[door_sensor_entity_id].last_changed) > as_timestamp(states[last_motion_helper_entity_id].state) }}
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ occupancy_helper_entity_id }}"

      - conditions:
          - condition: trigger
            id: ha_start
          - condition: template
            value_template: "{{ recheck_on_start }}"
        sequence:
          - if:
              - condition: state
                entity_id: "{{ motion_sensor_entity_id }}"
                state: "on"
            then:
              - service: input_boolean.turn_on
                target:
                  entity_id: "{{ occupancy_helper_entity_id }}"

  - if:
      - condition: template
        value_template: "{{ bypass_helper is defined and bypass_timeout_minutes > 0 }}"
    then:
      - delay:
          minutes: !input bypass_timeout_minutes
      - service: input_boolean.turn_off
        target:
          entity_id: "{{ bypass_helper_entity_id }}"
