blueprint:
  name: Lock Management (0.1.0rc10)
  description: lock Management 
  domain: automation
  source_url: https://github.com/asucrews/ha-blueprints/blob/main/automations/lock_management/lock_management.yaml
  input:
    witch_lock_name:
      name: Lock name
      description: Lock Entity
      selector:
        entity:
          domain:
            - lock
          multiple: false
    lock_auto_timer_helper:
      name: Lock Auto Timer
      description: Lock Auto Timer
      default: 0.0
      selector:
        number:
          mode: box
          min: 0.0
          max: 300.0
          unit_of_measurement: seconds
          step: 1.0

variables:
  witch_lock_name: !input witch_lock_name
  lock_auto_timer_helper: !input lock_auto_timer_helper

trigger:
  - platform: event
    event_type: lock_code_manager_lock_state_changed
    id: LCM Event
  - platform: state
    entity_id: !input lock_auto_timer
    from: active
    to: idle
    id: Timer Finished

action:
  choose:
    - conditions: []
      sequence: []

mode: queued
max: 5