name: Update Blueprints

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: write  # Grant write permissions

jobs:
  update-blueprints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full git history is fetched

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python scripts/update_blueprints.py

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "no changes"
            echo "::set-output name=changes::false"
          else
            echo "changes"
            echo "::set-output name=changes::true"
          fi

      - name: Commit changes
        if: steps.changes.outputs.changes == 'true'
        env:
          GIT_AUTHOR_EMAIL: action@github.com
          GIT_AUTHOR_NAME: GitHub Action
          GIT_COMMITTER_EMAIL: action@github.com
          GIT_COMMITTER_NAME: GitHub Action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Update blueprint list"
          git push
