name: Update Blueprints

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update-blueprints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run update script
        run: python update_blueprints.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update blueprint list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
